### PR TITLE
Enable the user to change the mappings (eg. if <Space> is already used)

### PR DESCRIPTION
**Pull request by sitaktif**
"""
Allow user-defined mappings

Allow to replace &lt;Space&gt;, &lt;S-Space&gt; and &lt;BS&gt; individually. The defaults
stay the same.
Add an option to disable the "non-GUI" mapping (by default, &lt;BS&gt;).
Clean things a bit: now gives a proper message if a key is already mapped.
"""

### CODE REVIEW

**Comment by graywh** [comment]
The use of &lt;Plug&gt; is good.

**Comment by sitaktif** [comment]
Thanks; 
btw speaking of  `<plug>`, people probably want to remember not to use noremap with it. It seems obvious when one thinks of it, but it is much less the case "in the middle of action"...

**Comment by sitaktif** [comment]
Any update?

**Comment by graywh** [comment]
I'd recommend using `:echom` for the warnings about keys already having mappings.  And bring this up in #vim to get spiiph's attention.

**Comment by mbadran** [comment]
+1 for this feature.

**Comment by graywh** [comment]
@sitaktif You should squash those commits and fix your email address to associate it with your github account

**Comment by sitaktif** [comment]
I've spent some time doing a bit of cleaning on space.vim global variables recently and I have got a few commits to propose (and the commits are properly separated this time). 

I'll close this pull request and open new ones.

Cheers,
Romain

**Comment by spiiph** [comment]
Thanks for your work. Feel free to poke me now and then about pulling your
changes. I'll try to have a look at it soon!

Henrik

**Pull request closed without merging**
